### ISSUE TITLE
Korean translation

### ISSUE THREAD

**Issue by mensch72** [pik-gane/vodle#139]
...is already in progress by Jinho. This is just to document that fact. @Jinho: could you assign yourself to this issue, please?

**Comment by diqnfl777** [comment]
I don't think I can, will you do it for me?

**Comment by diqnfl777** [comment]
The translation is finished, Here are some notes for future korean contributors:

- "wap" is translated as 승인 점수. approvals as 승인량 or 승인 수. If 승인 점수 doesn't seem to be a good translation for future people, just replacing it with "wap" seems fine as well.

- 선택지 for "options". "win" 하는 선택지들은 "채택"되었다고 통일시켜 표현하였습니다.

- acceptable was expressed as "용인되는". I'm not too happy with this word choice, But I couldn't think of a more natural word. Feel free to change this one if you have a good idea.

- delegate 는 "위임", delegate 는 "대표자"로 통일시켰습니다. "위임자"는 너무 부자연스러워서 이렇게 했는데... 이것도 더 좋은 의견이 있으시면 바꿔도 좋을것 같습니다.

**Comment by mensch72** [comment]
thank you for your work, Jinho
