### ISSUE TITLE
user can toggle showing of live results

### ISSUE THREAD

**Issue by mensch72** [pik-gane/vodle#165]
on the poll page, there is a toggle "live results", turned off by default.

- if on, everything appears as now
- if off, no approval bars, pie charts, written tally details, or "explain" buttons will be shown, no wap data will be fetched from the database (except maybe if one has delegated, to be able to show the delegate's rating?), and no tallying and resorting will be performed

at the beginning, it is off and the option sorting order is random.

rationale: turning it off should reduce the network activity, make it easier to focus on one's one preferences, and easier to move sliders when otherwise much resorting will happen.

**Comment by adrian-lison** [comment]
Yeah, aside from the efficiency gains, this will be helpful also for many users I believe.

Just as a side note:  a more general version of this would be an auto-update in regular intervals (e.g. every 5min, interval can be changed in the settings) + an "update now" button...

**Comment by adrian-lison** [comment]
"Assistiere mir" sounds a bit strange to me in German, is that still machine translation?

**Comment by mensch72** [comment]
i don't know of any better way of putting it... it is certainly better than "hilf mir", right?
