### ISSUE TITLE
users should not be able to add new options shortly before poll ends

### ISSUE THREAD

**Issue by mensch72** [pik-gane/vodle#167]
adding options stops 1/14 of the total running time before the poll ends, so that voters are not distracted by new options in the end and can focus on adjusting their final waps. this should also reduce the incentive of timing the addition of options strategically.

**Comment by adrian-lison** [comment]
Agree that this makes sense, however would consider using an absolute running time rather than a relative one... Or a combination of both, e.g.: `max(1/14 of total running time, min(15min, 9/10 of total running time))`.

**Comment by semla** [comment]
Pointers for implementing this?
After skimming through the code I gather [poll.service](https://github.com/pik-gane/vodle/blob/main/src/app/poll.service.ts) is the place?
Naively something like
```
      const time_to_disable_option_adding_ms = (due.getTime()-start_date.getTime())/14;
      window.setTimeout(()=>{  this.allow_adding_options = false}, time_to_disable_option_adding_ms);
```
in [set_timeouts()](https://github.com/pik-gane/vodle/blob/2c67255883241549531245d81fd855179f3ce276/src/app/poll.service.ts#L215)

**Comment by mensch72** [comment]
Hi @semla, thanks for offering to help!

I would probably start by doing the following:

- In `environment.ts`, add a parameter `no_more_options_time_fraction`, set to 1/14.
- In `poll.service.ts`, class `Poll`, add a property `can_add_options` similar to the existing property `is_ending_soon`, which returns True if the quotient between remaining time and total running time is larger than `environment.no_more_options_time_fraction`.
- Near the end of `poll.page.html`, make the ad option ng-container only show if `p.can_add_options` is True.

This will make sure the respective button is only shown if adding an option still is allowed. Later, we could make this even more safe by also doing the following:

- In `addoption-dialog.page.ts`, function `OK_button_clicked`, check again that `p.can_add_options` is True, and show an error message if not.

Alternatively to the latter, one could also do the following:

- In `addoption-dialog.page.ts`, function `ionViewDidEnter`, add another `setTimeout` like the one you sketched, and have it cancel the dialog when it is still open when the time is reached.

We don't need to adjust the `set_timeouts` function here since that is only for scheduling notifications, and I don't think we need to notify users that no further options can be added. Rather, we can can change the explanation text at the bottom of  `poll.page.html` to explain that adding options is only possible until so-and-so time.

Please don't hesitate getting back to me if any of this is unclear or seems nonsense :-)

**Comment by mensch72** [comment]
Hey @Held99 , sorry for taking so long, I was on vacation.
Yes, the issue is still up, so if you're still interested, go ahead!
Feel free to ask anything that is unclear, I will answer much faster now...

**Comment by Held99** [comment]
Hi @mensch72 , I think I have most of the functionality done and would I like to send it for review, however

> In addoption-dialog.page.ts, function OK_button_clicked, check again that p.can_add_options is True, and show an error message if not.

I don't know how you go about showing an error message in this project. Is there some sort of dialogue/popup service I'm not seeing? Thanks in advance.

**Comment by mensch72** [comment]
That sounds promising!
There is no such special service yet. I think it would suffice to just grey out the OK button and show a red message below it, like in an invalid form field, so that the only option that remains is the cancel button. 
Even better would of course be if the OK button would grey out immediately when the time is too late, not just when the user attempts to press the OK button. But I guess that would require some kind of repeated checks, say every second, mayby implemented by recursive calls to `setTimeout()`?
