### ISSUE TITLE
improve landing page

### ISSUE THREAD

**Issue by mensch72** [pik-gane/vodle#172]
on the landing page (www.vodle.it), several improvements could be made:

- the gallery of slogans below the main title and some other parts do not render well on **mobile** devices
- between title and gallery of slogans, some small set of motivating questions should appear that hints at possible use cases, probably selected from https://github.com/pik-gane/vodle/blob/main/USE_CASES.md
- in the "it's simple" and "how to help" sections, the **spacing around the icons** is bad

**Comment by parthmarfatia** [comment]
I can help you out with this. I am facing issues running this application in the local. Can you help me out with the steps?

**Comment by mensch72** [comment]
on the first bullet point: in my mobile, it renders like this:
![image](https://user-images.githubusercontent.com/22815964/178471190-1fdc3fa1-988c-4be1-bd7d-8c554bf800ac.png)
i.e., the images in the slogan gallery are cropped from both sides rather than shrunk to fit the screen width. maybe one can either make them shrink, or provide separate images for mobile devices, which are cropped in advance so that they show the slogan nicely. (currently the images are very wide but contain mostly unicolored space...)

**Comment by leighbriody** [comment]
Ill also have a look at this and see if there is anything I can help with !

**Comment by rakshitgondwal** [comment]
Can I try solving this issue too?

**Comment by mensch72** [comment]
Dear Rakshit, of course, why not! Thank you. I don't know how much progress Parth and Leigh have made already....

**Comment by leighbriody** [comment]
I am having some issues with this one sorry , changes I am making to the
index.html file don’t seem to reflect in the browser

**Comment by mensch72** [comment]
Maybe I shouldn't have used this AMP framework for the landing page after all, I don't understand it's logic either. It just seemed an easy start at the time...

**Comment by mensch72** [comment]
OK, so Rakshit has fixed the spacing issues, i.e. the third bullet point of the original list, and only the first two points remain in this issue.

**Comment by mensch72** [comment]
Hey Parth and Leigh, did you make some progress on the gallery part?

**Comment by ferrorenan** [comment]
Hey guys, I would like to solve this problem! I can!?

**Comment by mensch72** [comment]
Hi Renan @ferrorenan, yes of course, thank you! The first two items on the description remain unsolved:

- the gallery of slogans below the main title and some other parts do not render well on mobile devices
- between title and gallery of slogans, some small set of motivating questions should appear that hints at possible use cases, probably selected from https://github.com/pik-gane/vodle/blob/main/USE_CASES.md

The main file is src/assets/landing-page/index.html

**Comment by asumandang** [comment]
Is this open? I noticed that the last update on this issue was just last year?

**Comment by mensch72** [comment]
Hi @asumandang , yes, I haven't heard back from @ferrorenan again, so I assume the two bullet points from two comments above this comment are still unresolved.

**Comment by asumandang** [comment]
Good day, @mensch72 ! I tried to work on this ticket although I'm not sure if there's a design I should follow for the second bullet (adding set of motivating questions) and I'm also not that design savvy person. 

![image](https://github.com/pik-gane/vodle/assets/32838966/58b1290f-fb51-4dce-af51-a43e9761860c)

I was able to fix the gallery image on smaller screen width.
![image](https://github.com/pik-gane/vodle/assets/32838966/eb712ef2-5efe-4087-8e00-6f05917cdc24)

**Comment by mensch72** [comment]
Looks fine at first glance, will look more closely next week! Thank you again!!

**Comment by asumandang** [comment]
Hello @mensch72 ! Any news about the PRs I created? Was wondering because I haven't heard a feedback from you so far.

I hope you are okay and enjoyed your holidays last week! 😁

**Comment by mensch72** [comment]
Sorry for being so slow. I came back yesterday very late and had many meetings today. I will have a thorough look tomorrow!
