### ISSUE TITLE
require options to be unique within same poll

### ISSUE THREAD

**Issue by wjk36** [pik-gane/vodle#181]
Currently user can enter the same option twice for the same poll. Maybe display a warning and disable 'ready' button when two options are non-unique.

<img width="1042" alt="Screen Shot 2022-08-13 at 8 14 50 PM" src="https://user-images.githubusercontent.com/57546377/184520921-cc2f3a7f-ee4e-41c0-980a-3a58c39beb1a.png">

**Comment by mensch72** [comment]
Thank you @wjk36, this is an obvious bug I should have seen earlier!
To fix it, we need to add another validator in the respective forms in the draftpoll and addoption-dialog components, plus corresponding error messages.

**Comment by semla** [comment]
It is a start; added a custom validator, in its own file so it can be used in the addoption-dialog too. But haven't wrapped my head around that component, when is it used?

Other opinions?

**Comment by mensch72** [comment]
I managed to add the validator also to addoption-dialog now, using: `unique_name_validator$(of(this.p.oids.map(oid => this.p.options[oid].name)))`
