### ISSUE TITLE
Details Toggle Translation

### ISSUE THREAD

**Issue by ochan12** [pik-gane/vodle#220]
**Describe the bug**
When creating a poll/draft poll, the top right toggle doesn't translate 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'My polls'
2. Create a new or open a draft
3. You'll see the top right toggle has the `Details` text even when changing languages

**Expected behaviour**
It should be on the user preferred language

**Screenshots**
<img width="882" alt="image" src="https://user-images.githubusercontent.com/20117588/201337507-737301f9-21e2-40b0-a515-94740e6211f4.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser : Chrome

**Additional context**
I see that the the text is supposed to be translated, but the entry doesn't exist on any of the json translation files. 
```html
<span style="color: white" [innerHtml]="'details'|translate"></span>
```
The solution would be to create an entry under `draftpoll.details` on each language and change the tag to 
```html
<span style="color: white" [innerHtml]="'draftpoll.details'|translate"></span>
```

**Comment by mensch72** [comment]
Thanks for spotting this. Solved by commit 1395c3d931bada21bf2f4b590527a9c5437a6cc2 directly to main branch.
