### ISSUE TITLE
Can't choose the language on Chrome

### ISSUE THREAD

**Issue by Butanium** [pik-gane/vodle#252]
**Describe the bug**
I can't choose the language on Chrome, the drop-down menu doesn't show any option
**To Reproduce**
1. Go to https://vodle.osuosl.org/#/login/start/%252Fjoinpoll%252Fhttps%253A%25252F%25252Fvodle.osuosl.org%25252Fcouch%25252F%252Fnone%252F6121b4b4%252F3ef1053b68a7155a
2. Try to select a language
**Expected behavior**
I should be able to select a language

**Screenshots**

https://github.com/pik-gane/vodle/assets/55806347/0016f8bc-180f-4b98-90e5-5f972b0e0d1d

**Desktop (please complete the following information):**
 - OS:Kubuntu
 - Browser Chrome
 - Version115.0.5790.102 (64 bits)

**Comment by asumandang** [comment]
Hello @mensch72 ! I'm new to contributing to open source projects and I'm interested in taking this on.

**Comment by mensch72** [comment]
Wonderful! I'll assign your for now. You can just fork the repo and work on it. In the end, you do a pull request for me to review. If you have questions, feel free to ask. I might be a little slow to answer this week because of holidays, but I'll do my best :-)

**Comment by asumandang** [comment]
No worries. Enjoy your holidays! 😁 I created a pull request for the fix (with a signed commit) and signed the CLA. I hope I did not miss anything.
