### ISSUE TITLE
"show results" button and logics

### ISSUE THREAD

**Issue by mensch72** [pik-gane/vodle#27]
after poll has closed:
- when voter visits poll for the first time, ratings page is greyed out and overlayed with button "this poll is closed – show results?" that takes voter to the existing wheel-of-fortune animation
- when voter revisits poll later, only a snapshot of the final wheel position and result is shown on top of the voter's list of ratings (which is frozen then)

**Comment by masuri94** [comment]
After review of commit a8175aa issue can be closed

**Comment by mensch72** [comment]
duplicate of #51
