### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by mensch72** [pik-gane/vodle#55]

**Comment by ochan12** [comment]
Hi @mensch72 ! I'll work on this. One question though, the term `non-abstenionist` can be translated into Spanish it's seldom used. Would you consider that `active participant` or `participant that took part in` could represent `non-abstentionist participant` ?

**Comment by ochan12** [comment]
That's great! I had already started working on the translations in a forked repo in the file `src/assets/i18n/es.json`.  Is it possible to continue working there?

**Comment by mensch72** [comment]
I think that's OK but you won't profit from Crowdin features then. Your choice. For the reviewers I will load it into Crowdin later.

Am 10. November 2022 18:47:12 MEZ schrieb Mateo Ochandorena ***@***.***>:
>That's great! I had already started working on the translations in a
>forked repo in the file `src/assets/i18n/es.json`.  Is it possible to
>continue working there? 
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/pik-gane/vodle/issues/55#issuecomment-1310664055
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by ochan12** [comment]
No problem! I'll see the preview running the project
