### ISSUE TITLE
Password requirements

### ISSUE THREAD

**Issue by leander-j** [pik-gane/vodle#91]
The app doesn't allow non-alphanumeric characters and in that case states ***one*** capital/non-capital letter is required which can also be mis-read as "exactly one" …

**Comment by MaxBechthold** [comment]
+1

**Comment by mensch72** [comment]
Thanks you for this bug report!

Yes, the password-checking regular expression in login.page.ts should be adjusted to allow other characters, and the text of the error messages in en.json and de.json should be adjusted.

**Comment by mensch72** [comment]
Solved. Now arbitrary characters are allowed.
