### ISSUE TITLE
Delegation requirements

### ISSUE THREAD

**Issue by leander-j** [pik-gane/vodle#92]
When leaving the delegate's name field empty, it's not possible to click any of the button (to potentially give you an error message). The field is not on first sight recognizable as such. At least my focus is on the second field of the senders address.

Once the name field is clicked and left empty, the message `validation.delegate_nickname-required` can be read below. It should be replaced by a(nother) string.

**Comment by mensch72** [comment]
Thanks! 
The message problem can be fixed by comparing the translation keys in delegation-dialog.page.ts and en.json and de.json.
I have no idea how to fix the focus problem though.
Maybe these input fields could also use a different style (with a border around them?)

**Comment by mensch72** [comment]
Solved. (Left the field style untouched for now, but made sure focus sets correctly).
