### ISSUE TITLE
Expand/collapse option details

### ISSUE THREAD

**Issue by leander-j** [pik-gane/vodle#97]
When trying to expand/collapse the details of an option, I often hit the sliding bar instead since its activation area reaches until right below the expand/collapse button.

There could be more room given to the expand/collapse button. In addition its functionality could be expanded to the title text or the top row in general.

**Comment by mensch72** [comment]
Giving the button more space is difficult. Also moving it somewhere else is not convincing, I already tried several alternative positions. But making the whole title respond to clicks by expanding/collapsing seems a good idea and should be easy.

**Comment by mensch72** [comment]
Solved by making the whole option title respond and expand the details.
